CONSOLE_ENABLE = no
TRI_LAYER_ENABLE = no
COMBO_ENABLE = yes
REPEAT_KEY_ENABLE = yes
AUTOCORRECT_ENABLE = no
KEY_OVERRIDE_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
CAPS_WORD_ENABLE = yes
MOUSEKEY_ENABLE = yes

